---

- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  openssh_keypair:
    path: /home/ec2-user/.ssh/gitawx
    owner: ec2-user
    group: ec2-user

- name: Set owner and permission of the generated pub key
  file:
    path: /home/ec2-user/.ssh/gitawx.pub
    owner: ec2-user
    group: ec2-user
    mode: '777'